[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/jackc/pgx"
  version = "3.3.0"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"
