# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "CI & CD Pipeline"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PGUSER: postgres
      PGPASSWORD: password
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Postgres Client
      run: sudo apt-get install -y postgresql-client libpq-dev
    - name: Create Test Database
      run: make recreatedb
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'
        cache-dependency-path: "**/*.sum"
    - name: Install Test Runner
      run: go install github.com/onsi/ginkgo/ginkgo@v1.16.5
    - name: Run Test
      run: ginkgo -race -r
  
  release:
    if: github.ref_name == 'main'
    needs: [test]
    name: "Build and release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Docker image build & push  
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Git short sha
        id: git_context
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            -t danicaceres1998/pgreplay-go:${{ steps.git_context.outputs.short_sha }} \
            -t danicaceres1998/pgreplay-go:latest
          docker push danicaceres1998/pgreplay-go --all-tags
